name 'tomcat'
maintainer 'Charitra'
maintainer_email 'charitra.maharjan1@gmail.com'
license 'all_rights'
description 'Installs/Configures learn_tomcat'
long_description 'Installs/Configures learn_tomcat'
version '0.1.0'
